#!/usr/bin/python
# -*- coding: utf-8 -*-

import threading

from os import chdir, path

from server.chatserver import PushyChatServer, PushyChatRequestHandler

PUBLIC_DIRECTORY = path.abspath(path.join(path.dirname(__file__), 'public'))

if __name__ == '__main__':
    print '- serve content of: %s' % PUBLIC_DIRECTORY
    chdir(PUBLIC_DIRECTORY)
    purge_loop = threading.Thread(target=PushyChatRequestHandler.purge_loop)
    purge_loop.daemon = True
    purge_loop.start()
    server = PushyChatServer(('', 8000), PushyChatRequestHandler)
    server.serve_forever()
